GET http://localhost:3000/api/fakeUserTest
###
POST http://localhost:3000/api/fakeUserTest
###
PUT http://localhost:3000/api/fakeUserTest
###
DELETE http://localhost:3000/api/fakeUserTest
###
PATCH http://localhost:3000/api/fakeUserTest